apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server
  namespace: default
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      containers:
        - name: grpc-server
          env:
          image: yiyicai/grpc-server:0.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 10001
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-test-service
  namespace: default
spec:
  selector:
    app: grpc-server
  ports:
    - name: grpc
      port: 10001
      protocol: TCP